### ISSUE TITLE
`flutter pub run build_runner build` shows 'Deprecated' message

### ISSUE THREAD

**Issue by denxorz** [netglade/auto_mappr#69] opened 2023-05-16 12:06 UTC
Hello, 

It seems that `flutter pub run build_runner build` command from the README.md gives a deprecated message, as shown below. Using the second stated command `dart run build_runner build` does not give this message (as expected).

Do you recommend to use the `dart run build_runner build` command from now on, even for flutter projects?

```
C:\work\app-flutter>flutter pub run build_runner build 
Deprecated. Use `dart run` instead.
Building package executable... (21.1s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 673ms
[INFO] Precompiling build script... completed, took 9.8s

... snip ...

C:\work\app-flutter>flutter --version 
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (7 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1
```

**Comment by tenhobi** [comment] 2023-05-17 09:58
Hi @denxorz, I do not see this deprecation in Flutter 3.7.10 or 3.10.0. But we can investigate what is now the proper command to use. 

From json_serializable or freezed packages it seems they also suggest the same thing as we do. 🤷‍♂️ 

- https://pub.dev/packages/json_serializable#running-the-code-generator
- https://pub.dev/packages/freezed#install

So I am not really sure what is correct.

**Comment by tenhobi** [comment] 2023-06-21 11:48
Since we couldn't reproduce this error and no additional information was provided, I close it. Feel free to add some details if you feel this issue remains.

**Comment by denxorz** [comment] 2023-06-21 12:25
If I check the dart release notes it looks more like a bug over there:
`[#3847](https://github.com/Dart-Code/Dart-Code/issues/3847): Running build_runner tasks on the latest stable SDK no longer prints “Deprecated. Use dart run instead.”`
https://dartcode.org/releases/v3-36/

So I guess no documentation update is needed on this repo.

**Comment by tenhobi** [comment] 2023-06-21 17:45
I see, we can update that to only `dart/flutter run` for sure, thanks.

**Comment by tenhobi** [comment] 2023-08-29 07:16
Will be present in v2.

**Closed by tenhobi** 2023-08-29 07:16 UTC
Labels: documentation
