### ISSUE TITLE
Generation fails when required TARGET field doesn't exist in SOURCE even with whenNull

### ISSUE THREAD

**Issue by herna** [netglade/auto_mappr#148] opened 2023-11-02 10:25 UTC
Hi,

Imagine you have these 2 classes:

```
@freezed
class Equipment with _$Equipment {
  const factory Equipment({
    int id,
    int type,
  }) = _Equipment;
}

@freezed
class EquipmentForm with _$EquipmentForm {
  const factory EquipmentForm ({
    int id,
    required String name,
  }) = EquipmentForm ;
}
```

And your mapper is like this:

```
@AutoMappr([
  MapType<Equipment, EquipmentForm>(
    fields: [
      Field('name', whenNull: ''),
    ],
  ),
])
```

When running the generator, you get this message:

> Can't generate mapping Equipment → EquipmentForm as there is non mapped not-nullable required named parameter name

I'd say this should work and set the whenNull value, right?

Thanks.

**Comment by tenhobi** [comment] 2023-11-02 10:34
Hey, this is a duplicate of #29.

> Basically, this package states that it works with freezed, meaning that it can be both used together. Mapping have to be however specified on case to case basis, since I am not sure we can easily generate code that would support mapping of essentially disjunctive cases. So don't try to tell mappr "map A or B or C or D or E... into X or Y or Z..." but rather "map A to X, map B to Y, map C to Z, ..." and that will be both more clear to you as it will do exactly what you want anytime and also mappr don't have to do some black magic and guess :D 
>
> Similar thing also applies to sealed classes, where you also don't want to use that sealed class as a source or target but map it's specific types. We should probably clarify that more in docs. 🤔 

And yea, we should clarify that in docs more. 😅

**Comment by herna** [comment] 2023-11-02 10:43
Hi,

Ok I think I can solve it like this:

```
@AutoMappr([
  MapType<Equipment, EquipmentForm>(
    fields: [
      Field('name', custom: EquipmentMapper.mapName),
    ],
  ),
])

class EquipmentMapper extends $EquipmentMapper {
  static String mapName(Equipment equipment) => '';
}
```

Thanks.

**Closed** 2023-11-02 10:43 UTC
Labels: duplicate
